// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, non_constant_identifier_names
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjC_ubJZ1zq_MYAAAw4znUJexJfAwjxNg',
    appId: '1:999208036739:web:08224ad5eb8b03fb2daeb6',
    messagingSenderId: '999208036739',
    projectId: 'fir-test-108',
    authDomain: 'fir-test-108.firebaseapp.com',
    storageBucket: 'fir-test-108.appspot.com',
    measurementId: 'G-QGZXZKRHZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC13N_swF-fkIe_sQ6E2--CaJCtNuYHlqA',
    appId: '1:999208036739:android:7aae3f61111b229a2daeb6',
    messagingSenderId: '999208036739',
    projectId: 'fir-test-108',
    storageBucket: 'fir-test-108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQaNDgV_4_Io5FhuQXUNuUYF3dYZYHAF8',
    appId: '1:999208036739:ios:f34e09a81d93041f2daeb6',
    messagingSenderId: '999208036739',
    projectId: 'fir-test-108',
    storageBucket: 'fir-test-108.appspot.com',
    iosClientId: '999208036739-ehiciuu1dpgphnfepjq6c3j5femsdort.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest108',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQaNDgV_4_Io5FhuQXUNuUYF3dYZYHAF8',
    appId: '1:999208036739:ios:f34e09a81d93041f2daeb6',
    messagingSenderId: '999208036739',
    projectId: 'fir-test-108',
    storageBucket: 'fir-test-108.appspot.com',
    iosClientId: '999208036739-ehiciuu1dpgphnfepjq6c3j5femsdort.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest108',
  );
}
